[package]
name = "filtering-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
pot-head = { path = "../..", features = ["filter-ema", "filter-moving-avg", "hysteresis-threshold"] }
