[package]
name = "pot-head-interactive"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
pot-head = { path = "../.." }
crossterm = "0.29"
num-traits = { version = "0.2", default-features = false }
